[workspace]
members = [
    "syntex_cratesio_shim",
    "libarena",
    "libgraphviz",
    "librustc_data_structures",
    "librustc_errors",
    "librustc_index",
    "librustc_lexer",
	"librustc_macros",
	"librustc_target",
	"libserialize",
	"libsyntax",
	"libsyntax_pos",
]
