[package]
authors = ["The Rust Project Developers"]
name = "syntex_arena"
version = "0.60.0"

[lib]
name = "syntex_arena"
path = "src/lib.rs"

[dependencies]
syntex_data_structures = { path = "../syntex_data_structures" }